name: Deploy react app to GitHub Pages

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
        
    - name: Install 
      run: npm install
      
    - name: Fix 
      run: npm audit fix 
      
    - name: Up 
      run: npm install --save react react-dom react-scripts

    - name: Build 
      run: |
        npm install --save gh-pages
        npm run build
      
    - name: Echo 
      run: ls
      
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        #deploy_key: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: dest
